language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-lint
    - python: 3.5
      env: TOX_ENV=py35-lint
    - python: 2.7
      env: TOX_ENV=py27-lint-readme
    - python: 3.5
      env: TOX_ENV=py35-pytest
    - python: 2.7
      env: TOX_ENV=py37-pytest
    - python: 2.7
      env: TOX_ENV=py27
      services:
        - docker
    - python: 3.5
      env: TOX_ENV=py35
      services:
        - docker
  global:
    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist


install:
    - sudo rm /etc/boto.cfg
    - pip install tox
    - python setup.py install

script:
    - tox -e $TOX_ENV
    - python-codacy-coverage -r coverage.xml


